export const instructorCategories = [
  "Acro",
  "Ballet",
  "Ballroom",
  "Contemporary",
  "Dance fitness",
  "Hip hop",
  "Jazz",
  "Kids classes",
  "Latin",
  "Musical theatre",
  "Pilates",
  "Salsa",
  "Tap",
  "Wedding dance",
  "Yoga",
];

export const styleOptions = instructorCategories;

export const australianSuburbs = [
  "Adelaide, SA",
  "Albion, QLD",
  "Annerley, QLD",
  "Ashgrove, QLD",
  "Auchenflower, QLD",
  "Balmoral, QLD",
  "Bardon, QLD",
  "Bowen Hills, QLD",
  "Brisbane City, QLD",
  "Bulimba, QLD",
  "Cairns City, QLD",
  "Camp Hill, QLD",
  "Canberra, ACT",
  "Carindale, QLD",
  "Chermside, QLD",
  "Coorparoo, QLD",
  "Darwin City, NT",
  "Dutton Park, QLD",
  "East Brisbane, QLD",
  "Eight Mile Plains, QLD",
  "Everton Park, QLD",
  "Fortitude Valley, QLD",
  "Gold Coast, QLD",
  "Greenslopes, QLD",
  "Hawthorne, QLD",
  "Hobart, TAS",
  "Indooroopilly, QLD",
  "Kangaroo Point, QLD",
  "Kelvin Grove, QLD",
  "Logan Central, QLD",
  "Lutwyche, QLD",
  "Mackay, QLD",
  "Melbourne, VIC",
  "Milton, QLD",
  "Moorooka, QLD",
  "Morningside, QLD",
  "Mount Gravatt, QLD",
  "New Farm, QLD",
  "Newstead, QLD",
  "Paddington, QLD",
  "Perth, WA",
  "Red Hill, QLD",
  "Rockhampton, QLD",
  "South Brisbane, QLD",
  "Spring Hill, QLD",
  "St Lucia, QLD",
  "Sunnybank, QLD",
  "Sydney, NSW",
  "Toowong, QLD",
  "Toowoomba, QLD",
  "Townsville, QLD",
  "West End, QLD",
  "Woolloongabba, QLD",
  "Wooloowin, QLD",
];

export const serviceAreaOptions = australianSuburbs.filter((suburb) =>
  suburb.endsWith(", QLD")
);
